CREATE TABLE IF NOT EXISTS PRODUCTS (
      PRODUCTS_ID TEXT,
      PRODUCT_NAME TEXT,
      SUPPLIER_ID TEXT,
      CATEGORY_ID TEXT,
      UNIT TEXT,
      PRICE_REAL
      );

INSERT INTO PRODUCTS(PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID,
CATEGORY_ID, UNIT, PRICE_REAL) VALUES

('1', "XIAOMI", '67', '1', '10 BOXES* 10 BAGS', 20000),
('2', "IPHONE", '67', '1', '10 BOXES* 10 BAGS', 500000),
('3', "SAMSUNG", '5', '1', '10 BOXES* 10 BAGS', 300000),
('4', "GOOGLE", '5', '1', '10 BOXES* 10 BAGS', 200000),

SELECT COUNT(PRODUCT_ID) AS Product_count
FROM PRODUCTS;

SELECT AVG(PRICE) AS Average_price
FROM PRODUCTS;

SELECT SUM(PRICE) AS Total_Price
FROM PRODUCTS;

