CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY, 
    NAME TEST NOT NULL,
    ADRESS TEXT, 
    PHONE TEXT,
    AGE INTEGER

);
INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1', 'RAM', 'DELHI', '*********', 18), 
('2', 'DOMINIC', 'NAIROBI', '*********', 25),
('3', 'KAZIM', 'DAR', '*********', 14),
('4', 'BLAKE', 'DAR', '*********', 20),  
('5', 'SARA', 'WASHINGTON', '*********', 67),  

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE = 14 AND ADDRESS = 'DAR';
SELECT * FROM STUDENT WHERE NAME = 'BLAKE' OR ADDRESS = 'DAR'
SELECT * FROM STUDENT WHERE ADDRESS = 'DAR' (NAME = 'BLAKE' OR NAME = 'KAZIM'); 
