CREATE TABLE IF NOT EXISTS NOBEL_WIN (
   YEAR INTEGER,
   SUBJECT TEXT,
   WINNER TEXT,
   COUNTRY TEXT
);

INSERT INTO NOBEL_WIN(YEAR, SUBJECT, WINNER, COUNTRY) VALUES

(1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN'),
(1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE'),
(1971, 'PHYSICS', 'DENNIS GABOR', 'HUNGARY'),
(1971, 'CHEMISTRY', 'GERHARD HERZBERG', 'CANADA'),
(1972, 'LITERATURE', 'HEINRICH BOLL', 'GERMANY'),
(1972, 'ECONOMICS', 'KENNETH ARROW', 'USA'),
(1973, 'MEDICINE', 'KARL VON FRISCH', 'AUSTRIA'),
(1980, 'MEDICINE', 'BARUJ BENACERRAF', 'USA'),
(1981, 'PHYSICS', 'NICOLAAS BLOEMBERGEN', 'USA'),
(1975, 'PHYSICS', 'AAGE BOHR', 'DENMARK');

SELECT * 
FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%'
ORDER BY YEAR;

